[tool.poetry]
name = "datacollector"
version = "0.1.0"
description = ""
authors = ["Cholil Alfarizi <cholil.alfarizi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
